apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapeflow-http-worker
  namespace: scrapeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrapeflow-http-worker
  template:
    metadata:
      labels:
        app: scrapeflow-http-worker
    spec:
      initContainers:
        - name: wait-for-nats
          image: busybox
          command: ['sh', '-c', 'until nc -z scrapeflow-nats 4222; do echo waiting for nats; sleep 2; done']
        - name: wait-for-minio
          image: busybox
          command: ['sh', '-c', 'until nc -z scrapeflow-minio 9000; do echo waiting for minio; sleep 2; done']
      containers:
        - name: http-worker
          image: k4rth/scrapeflow-http-worker:main-1778439779-b32f5cc9c8c483e370a166f09645f3502da45a8c # {"$imagepolicy": "flux-system:scrapeflow-http-worker-policy"}
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          env:
            - name: NATS_URL
              value: "nats://scrapeflow-nats:4222"
            - name: MINIO_ENDPOINT
              value: "scrapeflow-minio:9000"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: scrapeflow-minio-credentials
                  key: rootUser
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: scrapeflow-minio-credentials
                  key: rootPassword
            - name: MINIO_BUCKET
              value: "scrapeflow-results"
            - name: MINIO_SECURE
              value: "false"
            - name: FETCH_TIMEOUT_SECS
              value: "30"
            - name: NATS_MAX_DELIVER
              value: "3"
            - name: CREDENTIALS_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: scrapeflow-app-secrets
                  key: credentials-encryption-key
