apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - test-app-image-automation.yaml
  - test-app-image-repository.yaml
  - test-app-image-update-automation.yaml
  - test-app-manifest.yaml