apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: gitops-test-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: gitops-test-app-repo

  policy:
    numerical:
      order: asc

  filterTags:
    # 1. Capture the branch 'main'
    # 2. Capture the timestamp digits into a group named 'ts' (?P<ts>...)
    # 3. Capture the sha (ignored for sorting, but kept in the tag)
    pattern: '^main-(?P<ts>[0-9]+)-(?P<sha>[a-f0-9]+)'

    # Sort using ONLY the captured 'ts' group
    extract: '$ts'