apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  # Name used to link to the ImagePolicy
  name: gitops-test-app-repo
  namespace: flux-system # Must be in the flux-system namespace
spec:
  # The image path on Docker Hub
  image: k4rth/gitops-test-app

  # How often to check the registry for new tags
  interval: 1m

  # Set provider if you were using a different registry like ECR or GCR
  # provider: generic

  # The tag pattern to filter.
  # We use '*' to look at all tags (i.e., all commit SHAs)
  tagSelector:
    pattern: '^main.*' # Assuming your CI tags images like main-abcdef123...

  # If your Docker Hub image was private, you would add a secretRef here:
  # secretRef:
  #   name: docker-pull-secret