apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/

  - infrastructure.yaml

  - test_app/

  - simple-app.yaml

  - jupyter/

  - new-relic-monitoring.yaml

  - mlflow/

  - traefik-config.yaml